service: unzip-large-file

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:custom.filesBucket}"
        - "arn:aws:s3:::${self:custom.filesBucket}/*"

custom:
  filesBucket: ${self:service}-${self:provider.stage}

functions:
  unzipFile:
    handler: unzip.handler
    events:
      - s3:
          bucket: ${self:custom.filesBucket}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            # - prefix: zipped/ #TODO uncomment this if you want to unzip files in specific folder
            - suffix: .zip

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.filesBucket}
